// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(MeekinFirewatchContext))]
    [Migration("20211020184837_RabatInitial")]
    partial class RabatInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("API.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AccessTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountCountry")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AngryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CareCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CrowdtangleUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalLink")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HahaCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LikeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkCaption")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoveCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostCreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SadCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int?>("ShareCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SocialMediaPlatform")
                        .HasColumnType("TEXT");

                    b.Property<long>("SocialMediaPlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubscriberCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThankfulCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WowCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("API.PostLabeling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AccessTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnalysisDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysisReport")
                        .HasColumnType("TEXT");

                    b.Property<int>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacebookDecision")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HumanTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Intent")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDangerous")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Justifications")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("Offensive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OffensiveContent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RabatLikelihoodHarm")
                        .HasColumnType("REAL");

                    b.Property<long>("RabatVirality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speaker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryAnalysis")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PostLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
